#!/usr/bin/env node
import {
  existsSync, mkdirSync, readdirSync, readFileSync,
  rmSync, writeFileSync, rmdirSync,
} from "node:fs";
import { dirname, join } from "node:path";

const ROLES_DIR = "agents/roles";
const CONFIG_FILE = "config/agents.json";
const MANIFEST_FILE = "config/.agents-manifest.json";
const CHECK = process.argv.includes("--check");

const BANNER_TEXT =
  "GENERATED by scripts/sync-agents.mjs — DO NOT EDIT. " +
  "Edit agents/roles/<role>/role.md or config/agents.json, then run `npm run sync:agents`.";
const MD_BANNER = `<!-- ${BANNER_TEXT} -->`;
const TOML_BANNER = `# ${BANNER_TEXT}`;

/* ---------- parsing ---------- */

// Strict on purpose: a role file that carries structure this parser cannot
// represent should fail loudly rather than lose it silently.
function parseFrontmatter(raw, path) {
  const text = raw.replace(/\r\n/g, "\n");
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) throw new Error(`${path}: no YAML frontmatter`);
  const meta = {};
  for (const line of m[1].split("\n")) {
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    const kv = line.match(/^([A-Za-z0-9_-]+)\s*:\s*(.*)$/);
    if (!kv) throw new Error(`${path}: unsupported frontmatter line: ${line}`);
    let v = kv[2].trim();
    if (/^(".*"|'.*')$/.test(v)) v = v.slice(1, -1);
    meta[kv[1]] = v;
  }
  for (const k of ["name", "description", "class"]) {
    if (!meta[k]) throw new Error(`${path}: frontmatter is missing \`${k}\``);
  }
  if (meta.type) {
    throw new Error(`${path}: \`type\` was replaced by \`class\` (readonly|verifier|implementer)`);
  }
  if (meta.description.includes("\n")) {
    throw new Error(`${path}: description must be a single line`);
  }
  return { meta, body: m[2].trim() };
}

/* ---------- serialisation ---------- */

// Single-quoted YAML: the only escape is '' for '. Survives colons, quotes and
// backslashes in descriptions, which JSON.stringify did not do reliably.
const yamlStr = (s) => `'${String(s).replace(/'/g, "''")}'`;
const tomlStr = (s) => JSON.stringify(String(s));
const yamlBlockList = (items) => items.map((i) => `  - ${i}`).join("\n");

function tomlMultiline(body) {
  if (!body.includes("'''")) return `'''\n${body}\n'''`;
  const escaped = body.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');
  return `"""\n${escaped}\n"""`;
}

function outPath(toolMeta, roleName) {
  return toolMeta.layout === "dir"
    ? join(toolMeta.out_dir, roleName, `${toolMeta.file_name}${toolMeta.ext}`)
    : join(toolMeta.out_dir, `${roleName}${toolMeta.ext}`);
}

/* ---------- renderers ---------- */

const renderers = {
  devin: (name, desc, cfg, body) => {
    let fm = `name: ${name}\ndescription: ${yamlStr(desc)}\n`;
    if (cfg.model) fm += `model: ${cfg.model}\n`;
    if (cfg["allowed-tools"]) {
      fm += `allowed-tools:\n${yamlBlockList(cfg["allowed-tools"])}\n`;
    }
    if (cfg.permissions) {
      fm += "permissions:\n";
      for (const [k, v] of Object.entries(cfg.permissions)) {
        fm += `  ${k}:\n${v.map((i) => `    - ${i}`).join("\n")}\n`;
      }
    }
    return `---\n${fm}---\n\n${MD_BANNER}\n\n${body}\n`;
  },

  antigravity: (name, desc, cfg, body) => {
    let fm = `name: ${name}\ndescription: ${yamlStr(desc)}\n`;
    // `tools` is deliberately optional. Antigravity hangs a subagent given an
    // unmapped tool name, so we only enumerate tools where we have verified
    // every name; otherwise the subagent inherits the full toolset.
    if (cfg.tools) fm += `tools:\n${yamlBlockList(cfg.tools)}\n`;
    fm += `subagent: ${cfg.subagent ?? true}\n`;
    fm += `mainAgent: ${cfg.mainAgent ?? false}\n`;
    if (cfg.model) fm += `model: ${cfg.model}\n`;
    if (cfg.commandExecutionPolicy) {
      // Quoted deliberately: YAML 1.1 parses a bare `off` as the boolean false,
      // which would silently turn the policy into something Antigravity never
      // defined. Same trap as `on`, `yes`, `no`.
      fm += `commandExecutionPolicy: ${yamlStr(cfg.commandExecutionPolicy)}\n`;
    }
    return `---\n${fm}---\n\n${MD_BANNER}\n\n${body}\n`;
  },

  claude: (name, desc, cfg, body) => {
    let fm = `name: ${name}\ndescription: ${yamlStr(desc)}\n`;
    if (cfg.model) fm += `model: ${cfg.model}\n`;
    if (cfg.effort) fm += `effort: ${cfg.effort}\n`;
    // Comma-separated is the documented form for .claude/agents/*.md, and it is
    // also the form Devin's importer is documented against.
    if (cfg.tools) fm += `tools: ${cfg.tools.join(", ")}\n`;
    if (cfg.disallowedTools) {
      fm += `disallowedTools: ${cfg.disallowedTools.join(", ")}\n`;
    }
    return `---\n${fm}---\n\n${MD_BANNER}\n\n${body}\n`;
  },

  cursor: (name, desc, cfg, body) => {
    let fm = `name: ${name}\ndescription: ${yamlStr(desc)}\n`;
    fm += `model: ${cfg.model ?? "inherit"}\n`;
    fm += `readonly: ${cfg.readonly ?? false}\n`;
    fm += `is_background: ${cfg.is_background ?? false}\n`;
    return `---\n${fm}---\n\n${MD_BANNER}\n\n${body}\n`;
  },

  codex: (name, desc, cfg, body) => {
    // Codex identifies an agent by `name`, not by filename.
    let out = `${TOML_BANNER}\n\n`;
    out += `name = ${tomlStr(cfg.name ?? name)}\n`;
    out += `description = ${tomlStr(desc)}\n`;
    if (cfg.model) out += `model = ${tomlStr(cfg.model)}\n`;
    if (cfg.model_reasoning_effort) {
      out += `model_reasoning_effort = ${tomlStr(cfg.model_reasoning_effort)}\n`;
    }
    if (cfg.sandbox_mode) out += `sandbox_mode = ${tomlStr(cfg.sandbox_mode)}\n`;
    out += `developer_instructions = ${tomlMultiline(body)}\n`;
    return out;
  },
};

/* ---------- main ---------- */

const config = JSON.parse(readFileSync(CONFIG_FILE, "utf8"));

const roles = readdirSync(ROLES_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => {
    const path = join(ROLES_DIR, e.name, "role.md");
    return parseFrontmatter(readFileSync(path, "utf8"), path);
  });

// Build every file in memory first. Nothing touches disk until we know the
// whole set renders — a half-written harness is worse than none.
const generated = new Map();
for (const { meta, body } of roles) {
  for (const [tool, toolMeta] of Object.entries(config.tool_meta)) {
    const cfg = config.tools[tool]?.[meta.class];
    if (!cfg) {
      throw new Error(
        `config/agents.json: tool "${tool}" has no entry for class ` +
          `"${meta.class}" (role ${meta.name}). Add one, or remove the tool.`,
      );
    }
    const render = renderers[tool];
    if (!render) throw new Error(`no renderer for tool "${tool}"`);
    generated.set(
      outPath(toolMeta, meta.name),
      render(meta.name, meta.description, cfg, body),
    );
  }
}

const previous = existsSync(MANIFEST_FILE)
  ? JSON.parse(readFileSync(MANIFEST_FILE, "utf8")).files ?? []
  : [];

if (CHECK) {
  const drift = [];
  for (const [path, content] of generated) {
    if (!existsSync(path)) drift.push(`missing: ${path}`);
    else if (readFileSync(path, "utf8") !== content) drift.push(`changed: ${path}`);
  }
  for (const path of previous) {
    if (!generated.has(path) && existsSync(path)) drift.push(`stale: ${path}`);
  }
  if (drift.length) {
    console.error("Generated agent profiles are out of date:\n" + drift.join("\n"));
    console.error("\nRun `npm run sync:agents`.");
    process.exit(1);
  }
  console.log(`in sync (${generated.size} profiles)`);
  process.exit(0);
}

// Delete only what we previously wrote. Never scan-and-sweep a shared directory.
for (const path of previous) {
  if (generated.has(path) || !existsSync(path)) continue;
  rmSync(path, { force: true });
  console.log("removed stale", path);
  try {
    rmdirSync(dirname(path)); // succeeds only if now empty
  } catch {
    /* directory still has content — leave it alone */
  }
}

for (const [path, content] of generated) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
  console.log("wrote", path);
}

writeFileSync(
  MANIFEST_FILE,
  JSON.stringify(
    { generator: "scripts/sync-agents.mjs", files: [...generated.keys()].sort() },
    null,
    2,
  ) + "\n",
  "utf8",
);
console.log(`manifest: ${generated.size} files`);
